### ISSUE TITLE
nginx 1.20.1 下，管理员页面打不开

### ISSUE THREAD

**Issue by fscarmen** [cokemine/hotaru-admin#1]
这次我没有安装宝塔，按你的建议直接在 nginx.org/packages/debian 拉库安装，是 nginx 1.20.1 ，然后前端能正常显示，管理员那里的 login 进去之后的 Dashboard、Statistics 和 Alert 都正常，就是第二项 Management 变成白板，按f12截图如下

![image.png](https://i.loli.net/2021/09/24/18dw2lPuIUHoLeQ.png)

**Comment by cokemine** [comment]
上次更新前端的问题。更新一下 v1.1.0-alpha.6 应该就修复了
`docker pull cokemine/nodestatus@latest`

**Comment by fscarmen** [comment]
我该如何更新呢？重拉docker?

神楽坂みずき ***@***.***> 于2021年9月24日周五 下午7:44写道：

**Comment by cokemine** [comment]
@fscarmen 
```
docker pull cokemine/nodestatus@latest
```
然后进入有 docker-compose.yml的文件夹重新执行`docker compose up -d` 就更新了
